### ISSUE TITLE
BASE req.

### ISSUE THREAD

**Issue by MonikaBosaniova** [MonikaBosaniova/NebulaBrews#2]
- [x]  Must be playable on (PC or WebGL) and Android
- [ ] Must contain reasonable sound effects and music. You can download a lot of free sounds 
and music from Freesound

- [ ]  Must be stable and playable at reasonable FPS on at least Full HD (= 1920x1080 PC)
- [ ] UI that adapts for different reasonable screen sizes (e.g., 1920x1080 PC, 1080x2400 
Android, …)

- The UI should contain a somewhat interesting main menu and settings menu 
(e.g., more than just pure buttons).
 

- [ ]   Non-trivial use of at least 1 plugin (e.g., DOTween, Cinemachine, UI Toolkit, …)

- [ ]  Non-trivial use of Editor Extensions, so your game can be easily extensible for a game 
designer. 

- [x] Game controls using new input system Input System | 1.7.0
