### ISSUE TITLE
ADDITIONAL req.

### ISSUE THREAD

**Issue by MonikaBosaniova** [MonikaBosaniova/NebulaBrews#4]
- [ ] Implement Save/Load for your game
- [ ]  Use particle system (Introduction to Particle Systems - Unity Learn) for effects. 
- [x] Create a 3D game (yes, creating a 3D game is generally more difficult than 2D so one additional requirement is for free) 

- [ ] Extensive polish at the end of development (Close to production level on small scale)
